# Generated by Django 4.2 on 2024-04-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_topping_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='sign.topping'),
        ),
    ]
